/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solent_campers;

import java.awt.FlowLayout;
import javax.swing.JFrame;

/**
 *
 * @author kaur
 */
public class AdminForm extends javax.swing.JFrame {

    /**
     * Creates new form AdminForm
     */
    AddCAmpSite acs;
    RemoveCampsite rcs;
    AddVan av;
    RemoveVan rv;

    public AdminForm() {
        initComponents();
        acs = new AddCAmpSite();
        rcs = new RemoveCampsite();
        av = new AddVan();
        rv = new RemoveVan();
        temppanel.setLayout(new FlowLayout(FlowLayout.LEFT));
        temppanel.add(acs);
        temppanel.add(rcs);
        temppanel.add(av);
        temppanel.add(rv);
        acs.setVisible(false);
        rcs.setVisible(false);
        av.setVisible(false);
        rv.setVisible(false);
          this.setExtendedState(JFrame.MAXIMIZED_BOTH); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        temppanel = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mn_addcs = new javax.swing.JMenuItem();
        mn_del_cs = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        mn_add_van = new javax.swing.JMenuItem();
        mn_del_van = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 255, 204));

        javax.swing.GroupLayout temppanelLayout = new javax.swing.GroupLayout(temppanel);
        temppanel.setLayout(temppanelLayout);
        temppanelLayout.setHorizontalGroup(
            temppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        temppanelLayout.setVerticalGroup(
            temppanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        jMenu1.setBackground(new java.awt.Color(204, 255, 204));
        jMenu1.setText("Manage Camp Site");

        mn_addcs.setText("Add Campsite");
        mn_addcs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_addcsActionPerformed(evt);
            }
        });
        jMenu1.add(mn_addcs);

        mn_del_cs.setText("Remove Campsite");
        mn_del_cs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_del_csActionPerformed(evt);
            }
        });
        jMenu1.add(mn_del_cs);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Manage Van");

        mn_add_van.setText("Add Van");
        mn_add_van.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_add_vanActionPerformed(evt);
            }
        });
        jMenu2.add(mn_add_van);

        mn_del_van.setText("Remove Van");
        mn_del_van.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mn_del_vanActionPerformed(evt);
            }
        });
        jMenu2.add(mn_del_van);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Logout");

        jMenuItem2.setText("Logout");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem2);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(temppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(temppanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mn_addcsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_addcsActionPerformed
        // TODO add your handling code here:
        
        acs.setVisible(true);
        rcs.setVisible(false);
        av.setVisible(false);
         rv.setVisible(false);
    }//GEN-LAST:event_mn_addcsActionPerformed
    
    private void mn_del_csActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_del_csActionPerformed
        // TODO add your handling code here:
        rcs.setVisible(true);
        acs.setVisible(false);
        av.setVisible(false);
         rv.setVisible(false);
    }//GEN-LAST:event_mn_del_csActionPerformed
    
    private void mn_add_vanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_add_vanActionPerformed
        // TODO add your handling code here:
        av.setVisible(true);
        rv.setVisible(false);
        acs.setVisible(false);
        rcs.setVisible(false);
    }//GEN-LAST:event_mn_add_vanActionPerformed

    private void mn_del_vanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mn_del_vanActionPerformed
        // TODO add your handling code here:
         av.setVisible(false);
        rv.setVisible(true);
        acs.setVisible(false);
        rcs.setVisible(false);
    }//GEN-LAST:event_mn_del_vanActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new MainForm().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            
            public void run() {
                new AdminForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem mn_add_van;
    private javax.swing.JMenuItem mn_addcs;
    private javax.swing.JMenuItem mn_del_cs;
    private javax.swing.JMenuItem mn_del_van;
    private javax.swing.JPanel temppanel;
    // End of variables declaration//GEN-END:variables
}
