/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solent_campers;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solent_campers.Modal.camper_vans;

/**
 *
 * @author kaur
 */
public class RemoveVan extends javax.swing.JPanel {

    /**
     * Creates new form RemoveVan
     */
    CamperVanHelper cvh;

    public RemoveVan() {
        initComponents();
        cvh = new CamperVanHelper();
        fillCombo();
        fillTAble();
    }

    public void fillCombo() {
        ArrayList<camper_vans> vanlist = cvh.getAll();
        cbvanID.removeAllItems();
        for (int i = 0; i < vanlist.size(); i++) {
            int id = vanlist.get(i).getCv_id();
            cbvanID.addItem(id);

        }
    }

    private void fillTAble() {
        ArrayList<camper_vans> sitelist = cvh.getAll();
        String col[] = {"id", "Car Type", "Status"};
        DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (int i = 0; i < sitelist.size(); i++) {
            int id = sitelist.get(i).getCv_id();
            String type = sitelist.get(i).getType();
            String sts = sitelist.get(i).getStatus();

            Object[] data = {id, type, sts};

            tableModel.addRow(data);

        }
        tbl_van.setModel(tableModel);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cbvanID = new javax.swing.JComboBox();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_van = new javax.swing.JTable();
        btnDel = new javax.swing.JButton();
        btnRef = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel2.setText("Select Van ID");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Remove camper Van");

        cbvanID.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbvanIDItemStateChanged(evt);
            }
        });
        cbvanID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbvanIDActionPerformed(evt);
            }
        });

        tbl_van.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_van);

        jScrollPane2.setViewportView(jScrollPane1);

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        btnRef.setText("Refresh");
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbvanID, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnRef)
                                .addGap(42, 42, 42)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbvanID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef))
                .addGap(30, 30, 30)
                .addComponent(btnDel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbvanIDItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbvanIDItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbvanIDItemStateChanged

    private void cbvanIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbvanIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbvanIDActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:

        String selectedID = cbvanID.getSelectedItem().toString();
        cvh.deleteVan(Integer.parseInt(selectedID));
        JOptionPane.showMessageDialog(this, "Data Inserted Succcessfully!!");
        fillTAble();
    }//GEN-LAST:event_btnDelActionPerformed

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        // TODO add your handling code here:
        fillCombo();
        fillTAble();
    }//GEN-LAST:event_btnRefActionPerformed
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRef;
    private javax.swing.JComboBox cbvanID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_van;
    // End of variables declaration//GEN-END:variables
}
