/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package solent_campers;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import solent_campers.Modal.camping_sites;

/**
 *
 * @author kaur
 */
public class RemoveCampsite extends javax.swing.JPanel {

    /**
     * Creates new form RemoveCampsite
     */
    CampingSiteHelper csh;
   

    public RemoveCampsite() {
        initComponents();
        csh = new CampingSiteHelper();
        fillCombo();
        fillTAble();
    }

   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbCampNms = new javax.swing.JComboBox();
        btnDel = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_site = new javax.swing.JTable();
        btnRef = new javax.swing.JButton();

        setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Remove Campsite");

        jLabel2.setText("Select Camp Name");

        cbCampNms.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbCampNmsItemStateChanged(evt);
            }
        });
        cbCampNms.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCampNmsActionPerformed(evt);
            }
        });

        btnDel.setText("Delete");
        btnDel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDelActionPerformed(evt);
            }
        });

        tbl_site.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_site);

        jScrollPane2.setViewportView(jScrollPane1);

        btnRef.setText("Refresh");
        btnRef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDel)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbCampNms, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 109, Short.MAX_VALUE)
                                .addComponent(btnRef)))))
                .addContainerGap(38, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbCampNms, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRef))
                .addGap(30, 30, 30)
                .addComponent(btnDel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbCampNmsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCampNmsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCampNmsActionPerformed

    private void btnDelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDelActionPerformed
        // TODO add your handling code here:

        String selectedID = cbCampNms.getSelectedItem().toString();
        csh.deleteSite(Integer.parseInt(selectedID.split(" ")[0]));
        JOptionPane.showMessageDialog(this, "Data Inserted Succcessfully!!");
        fillTAble();
    }//GEN-LAST:event_btnDelActionPerformed
    private void fillTAble() {
        ArrayList<camping_sites> sitelist = csh.getAll();
 String col[] = {"id", "Site Name", "Region"};
    DefaultTableModel tableModel = new DefaultTableModel(col, 0);
        for (int i = 0; i < sitelist.size(); i++) {
            int id = sitelist.get(i).getCs_id();
            String name = sitelist.get(i).getCamping_sites();
            String region = sitelist.get(i).getRegion();

            Object[] data = {id, name, region};

            tableModel.addRow(data);

        }
        tbl_site.setModel(tableModel);
    }
    private void cbCampNmsItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbCampNmsItemStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCampNmsItemStateChanged

    private void btnRefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefActionPerformed
        // TODO add your handling code here:
        fillCombo();
        fillTAble();
    }//GEN-LAST:event_btnRefActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnRef;
    private javax.swing.JComboBox cbCampNms;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tbl_site;
    // End of variables declaration//GEN-END:variables

    private void fillCombo() {

        ArrayList<camping_sites> sitelist = csh.getAll();
        cbCampNms.removeAllItems();
        for (int i = 0; i < sitelist.size(); i++) 
        {
            int id = sitelist.get(i).getCs_id();
            String name = sitelist.get(i).getCamping_sites();
            cbCampNms.addItem(id + " " + name);

        }
    }
}
